# Generated by Django 3.1.7 on 2021-03-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('stoke', models.IntegerField()),
                ('image_urls', models.CharField(max_length=2000)),
            ],
        ),
    ]
